"""add assigned_dermatologist_id to users

Revision ID: 751dd71eca37
Revises: c1056097d959
Create Date: 2026-07-06 22:12:16.346283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '751dd71eca37'
down_revision: Union[str, None] = 'c1056097d959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('assigned_dermatologist_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['assigned_dermatologist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'assigned_dermatologist_id')
    # ### end Alembic commands ###
