"""baseline

Revision ID: c1056097d959
Revises: 
Create Date: 2026-07-06 22:11:13.474459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1056097d959'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('assigned_dermatologist_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['assigned_dermatologist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'assigned_dermatologist_id')
    # ### end Alembic commands ###
